[2024-07-18T20:05:23.091+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: crypto_pipeline.fetch_and_load scheduled__2023-12-12T12:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
